drop table Core.StudentEnrolment;
drop table Core.Student;
drop table Core.Program;
drop table Core.Enrolment;
drop table Core.Instructor;
drop table Core.Course;
drop table Core.Department;
drop table Core.Faculty;
drop table Core.AcademicSession;